apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alerts
  namespace: monitoring
  labels:
    role: alert-rules
spec:
  groups:
    - name: example.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High CPU usage detected"
            description: "Pod {{ $labels.pod }} is using more than 80% CPU."
