apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.32.0"
  values:
    adminPassword: "admin"
    service:
      type: NodePort
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
