apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "9.4.0"
  values:
    auth:
      rootPassword: "my-secret-password"
    primary:
      persistence:
        enabled: true
        size: 8Gi
