apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.2.0"
  values:
    auth:
      postgresPassword: "my-secret-password"
    primary:
      persistence:
        enabled: true
        size: 8Gi
