apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-releases/prometheus.yaml
  - helm-releases/loki.yaml
  - helm-releases/grafana.yaml
  - helm-releases/mysql.yaml
  - helm-releases/postgres.yaml
  - configmaps/grafana-dashboards.yaml
  - alerts/alert-rules.yaml
